### ISSUE TITLE
La finestra dei commenti Disqus non si formatta al 55% di larghezza

### ISSUE THREAD

**Issue by davideriboli** [davideriboli/davideriboli.github.io#1]
I commenti funzionano (ne ho messi alcuni di test in [questa discussione](https://davideriboli.github.io/articles/videomapping/integrazione-Resolume-Quartz-Composer)) ma eccede la main column (55% di larghezza).

**Comment by valentinarachiele** [comment]
Sistemato cambiando `div.disqus_thread` in `div#disqus_thread` nel CSS (è un id, non una classe).
